module Irozuku
  class Configuration
    public

    @colors: Hash[Symbol, String]
    @reset_sequence: ("enabled" | "disabled")
    @ansi_sequence: ("enabled" | "disabled")

    def colors: () -> Hash[Symbol, String]
    def reset_sequence: () -> ("enabled" | "disabled")
    def ansi_sequence: () -> ("enabled" | "disabled")

    def colors=: (Hash[Symbol, String] colors) -> void
    def reset_sequence=: (("enabled" | "disabled")) -> void
    def ansi_sequence=: (("enabled" | "disabled")) -> void

    private

    def initialize: () -> void
  end
end
