module Irozuku
  module Constants
    ANSI_ESC_SEQUENCE: String

    ANSI_RESET_SEQUENCE: String

    EIGHT_COLOR_MAP: Hash[Symbol, String]

    HEX_COLOR_MAP: Hash[Symbol, String]

    TEXT_DECORATION_MAP: Hash[Symbol, { code: String, reset: String }]
  end
end
